version: "3.1"

services:
  bitcoind:
    restart: always
    build: .
    volumes:
      - ./data:/data
    ports:
      - 8333:8333
    logging:
      options:
        max-size: "50m"
        max-file: "2"
